# **Modul 1 Data Mining 2020 "Numpy Array"**

## **1D Numpy Array**

Array NumPy mirip dengan list. Biasanya **ukurannya tetap** dan setiap **elemen bertipe sama.** Untuk membuat array NumPy kita terlebih dahulu harus mengimpor NumPy:

In [0]:
import numpy as np 

In [0]:
x = [1, 2, 3, 4, 5]
x

[1, 2, 3, 4, 5]

In [0]:
a = np.array(x)
a

array([1, 2, 3, 4, 5])

In [0]:
type(a)

numpy.ndarray

In [0]:
type(x)

list

Untuk mengkases elemen dari numpy array dapat menggunakan kurung siku diisi oleh index tujuan. `[<index>]`

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneNp.png" width="500" />

In [0]:
print("a[0]:", a[0])
print("a[1]:", a[1])

a[0]: 1
a[1]: 2


Karena tipe data dari elemen NumPy Array itu sama maka dapat menggunakan atribut `dtype` untuk mengetahui tipe data dari elemen `np.array()`.

In [0]:
a.dtype

dtype('int64')

### **Assign value**

Kita dapat mengubah nilai dari np array perhatikan contoh berikut :

In [0]:
print("Before Updating",a)
a[0]=100
print("After Updating",a)

Before Updating [1 2 3 4 5]
After Updating [100   2   3   4   5]


### **Slicing**

Kita dapat membuat np array baru yang berisi beberapa anggota elemen dari np array lainnya. Cukup gunakan `[:]` untuk melakukan slicing di ikuti index tujuan.

In [0]:
b = a[1:4]
print(b)
b = a[-4:-2]
print(b)
b = a[:3]
print(b)
b = a[2:]
print(b)
b = a[:]
print(b)

[2 3 4]
[2 3]
[100   2   3]
[3 4 5]
[100   2   3   4   5]


Dengan menggunakan slicing kita juga bisa mengubah isi np array sesuai keinginan kita perhatikan code berikut:

In [0]:
a[2:4] = 300, 400
a

array([100,   2, 300, 400,   5])

Anda juga dapat mengakses dan menggubah nilai np array menggunakan list.

In [0]:
my_list = [0, 2, 3]
c = a[my_list]
c

array([100, 300, 400])

In [0]:
a[my_list] = 5000
a

array([5000,    2, 5000, 5000,    5])

### **NumPy Array Operations**

**Basic Operations**

In [0]:
# Dapatkan jumlah elemen dalam array:
print(a.size)

# ndim digunakan untuk mendapatkan jumlah sumbu atau dimensi yang disebut pangkat:
print(a.ndim)

# Atribut "shape" adalah tupel bilangan bulat yang menunjukkan ukuran array di setiap dimensi:
print(a.shape)

# Dapatkan nilai mean dari elemen numpy array:
print(a.mean())

# Dapatkan standar deviasi dari elemen numpy array:
print(a.std())

# Dapatkan nilai terbesar dari numpy array:
print(a.max())

# Dapatkan nilai terkecil dari numpy array:
print(a.min())

5
1
(5,)
3001.4
2447.775283803642
5000
2


**Simple Math Operations**

In [0]:
u = np.array([1, 2, 3, 4])
v = np.array([3, 1, 4, 2])

In [0]:
# Kita dapat menambahkan dua array dan menetapkannya ke z:
z = u + v
print("Penambahan dua array",z)

# Hitung produk dari dua array numpy:
z = u * v
print("Perkalian dua array",z)

# Hitung dot product:
print("Dot product matrix",np.dot(u, v))

# Kita bisa mengalikan setiap elemen dalam array dengan konstanta:
z = 2 * u
print("Perkalian array dengan bilangan bulat",z)

z = 2.3 * u
print("Perkalian array dengan bilangan desimal",z)

# Tambahkan konstanta ke array:
u = u + 5
print("Penambahan array dengan konstanta",u)

# Pengurangan konstanta ke array:
u = u - 5
print("Pengurangan array dengan konstanta",u)

Penambahan dua array [4 3 7 6]
Perkalian dua array [ 3  2 12  8]
Dot product matrix 25
Perkalian array dengan bilangan bulat [2 4 6 8]
Perkalian array dengan bilangan desimal [2.3 4.6 6.9 9.2]
Penambahan array dengan konstanta [6 7 8 9]
Pengurangan array dengan konstanta [1 2 3 4]


**Perhatikan animasi berikut untuk operasi array dengan konstanta**

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneAdd.gif" width="500" />

### **Linspace**

Fungsi yang berguna untuk lainnya adalah "linespace". Linespace mengembalikan angka yang diberi spasi secara merata selama interval yang ditentukan. Kami menentukan titik awal dari urutan dan titik akhir dari urutan. Parameter "num" menunjukkan Jumlah sampel yang akan dihasilkan:

In [0]:
# Membuat array dengan 9 elemen dari rentang [-2, 4]
np.linspace(-2, 4, num=9)

array([-2.  , -1.25, -0.5 ,  0.25,  1.  ,  1.75,  2.5 ,  3.25,  4.  ])

## **2D Numpy Array**

In [0]:
import numpy as np 
import matplotlib.pyplot as plt

Perhatikan list `a`, list berisi tiga list bersarang masing-masing **dengan ukuran yang sama.**

In [0]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Kita dapat melakukan cast dari list ke sebuah Numpy Array perhatikan berikut. ***Setiap elemen harus tipe yang sama***:

In [0]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

**Basic Operations**

In [0]:
A.ndim

2

In [0]:
A.shape

(3, 3)

In [0]:
A.size

9

### **Accessing different elements of a Numpy Array**

Kita dapat menggunakan tanda kurung siku `[ ]` untuk mengakses berbagai elemen array. Korespondensi antara kurung siku `[ ]`, list dan representasi ditunjukkan pada gambar berikut untuk array 3x3:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoEg.png" width="500" />

Sebagai contoh misalkan kita ingin mengakses nilai di baris ke 2 dan kolom ke 3 dari suatu matriks 2D seperti pada figur dibawah :

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFT.png" width="400" />

In [0]:
# ada dua notasi yang dapat anda gunakan
print("A[1, 2] = ",A[1, 2])
print("A[1][2] = ",A[1][2])

A[1, 2] =  23
A[1][2] =  23


Kita bisa menggunakan slicing untuk mengakses multi elemen dari suatu array multi dimensi. Perhatikan demonstrasi berikut:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFSF.png" width="400" />

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoTST.png" width="400" />

In [0]:
# ada dua notasi yang dapat anda gunakan

print("A[0][0:2] = ",A[0][0:2])
print("A[1:, 2] = ",A[1:, 2])

A[0][0:2] =  [11 12]
A[1:, 2] =  [23 33]


**Simple Math Operations**

In [0]:
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])
print(X)
print("\n",Y)

[[1 0]
 [0 1]]

 [[2 1]
 [1 2]]


In [0]:
# Add X and Y
Z = X + Y
print(Z)

[[3 1]
 [1 3]]


**Matrix multiplication with scalar**

Mengalikan numpy array dengan skalar identik dengan mengalikan matriks dengan skalar. Jika kita mengalikan matriks Y dengan skalar 2, kita cukup mengalikan setiap elemen dalam matriks dengan 2 seperti yang ditunjukkan pada gambar.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoDb.png" width="500" />

**Multiplication 2 matrix**

In [0]:
# Multiply Y with 2
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoMul.png" width="500" />

In [0]:
# Multiply X with Y
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

**Operasi dot product matriks**

In [0]:
# Definisi matirks
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [0]:
# Definisi matirks
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [0]:
# Calculate the dot product
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

**Transpose Matrix**

In [0]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [0]:
# Get the transposed of C
C.T

array([[1, 2, 3],
       [1, 2, 3]])

###Materi lebih tentang numpy dapat diakses [disini](https://docs.scipy.org/doc/numpy/user/quickstart.html)
---